DesignTracer/DesignTracer/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DesignTracer/app/urls.py
from django.urls import path
from . import views
from DesignTracer import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views

app_name = "app"
urlpatterns = [
    path('',views.index, name='index'),
    path('users/<int:pk>/',views.users_detail, name='users_detail'),
    path('login/',auth_views.LoginView.as_view(template_name="app/login.html"), name="login"),
    path('logout/',auth_views.LogoutView.as_view(), name="logout"),
    path('signup/', views.signup, name='signup'),
    path('images/<int:pk>/', views.images_detail, name="images_detail"),
    path('images/<int:pk>/delete/', views.images_delete, name="images_delete"),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DesignTracer/app/models.py
from django.db import models
from django.contrib.auth.models import User

class Image(models.Model):
    title = models.CharField(max_length=150)
    theme = models.TextField(blank=True)
    break_down = models.TextField(blank=True)
    key_point = models.TextField(blank=True)
    image_f = models.ImageField(upload_to='../images')
    created_at = models.DateTimeField(auto_now=True)
    user =  models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

DesignTracer/app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Image

class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'theme', 'break_down', 'key_point']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': '名前/タイトル'}),
            'theme': forms.Textarea(
                attrs={'placeholder': '主張の理解：テーマ、伝えたいことは？', 'rows': "1"}),
            'break_down': forms.Textarea(
                attrs={'placeholder': '分析/言語化：レイアウト・余白/配色/文字組み/あしらい', 'rows': "5"}),
            'key_point': forms.Textarea(
                attrs={'placeholder': '抽象化：外せないキーになる部分は？', 'rows': "1"}),                         
        }

DesignTracer/app/views.py
from django.shortcuts import get_object_or_404,redirect,render
from .models import Image
from django.contrib import messages
import os
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from .forms import ImageForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login

# Create your views here.
def index(request):
    if request.method == "POST":
        updata = request.FILES['image']
        form = ImageForm(request.POST, request.FILES)
        if updata != None:
            fs = FileSystemStorage()
            filename = fs.save(updata.name, updata)
            uploaded_file_url = fs.url(filename)
            img = form.save(commit = False)
            img.user = request.user
            img.image_f = uploaded_file_url
            print("uploaded_file_url:",uploaded_file_url)
            print("image_f:",img.image_f)
            print("title:",img.title)
            img.save()
            images = Image.objects.all().order_by("-created_at")
        return render(request, 'app/index.html', {'images':images,'form':form})
    else:
        images = Image.objects.all().order_by("-created_at")
        form = ImageForm()
        return render(request, 'app/index.html', {'images':images,'form':form})

def images_detail(request,pk):
    image = get_object_or_404(Image,pk=pk)
    return render(request,'app/images_detail.html', {'image':image})

def images_delete(request,pk):
    form = ImageForm()
    images = Image.objects.all().order_by("-created_at")
    image = get_object_or_404(Image,pk=pk)
    image.delete()
    return render(request, 'app/index.html', {'images':images,'form':form})
    # return redirect('app:users_detail',request.user.id)

def users_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    images = Image.objects.all().order_by("-created_at")
    return render(request, 'app/mypage.html', {'user':user, 'images':images})

def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            input_username = form.cleaned_data['username']
            input_password = form.cleaned_data['password1']
            new_user = authenticate(username=input_username, password=input_password)
            if new_user is not None:
                login(request, new_user)
                return redirect('app:users_detail', pk=new_user.pk)
    else:
        form = UserCreationForm()
    return render(request, 'app/signup.html', {'form':form})

DesignTracer/app/templates/app/base.html
{% load static %}

{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{% load bootstrap_toolkit %}


<!DOCTYPE html>
<html>

<head>
    <title>DesignTracer</title>
</head>

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">


<body>
    <header>
        <dic class="container">
            <h1><a href="{% url 'app:index' %}">DesignTracer</a></h1>
            <div class="header-menu">
                {% if request.user.is_authenticated %}
                    <a href="{% url 'app:users_detail' request.user.id %}">マイページ</a>
                    <a href="{% url 'app:logout' %}">ログアウト</a>
                {% else %}
                    <a href="{% url 'app:signup' %}">サインアップ</a>
                    <a href="{% url 'app:login' %}">ログイン</a>
                {% endif %}
            </div>
        </dic>
    </header>
    <div class="container">
        {% for message in message %}
            <p class="message-success">{{ message }}</p>
        {% endfor %}
        {% block content %}{% endblock %}
    </div>
</body>

<script type="text/javascript" src="{% static 'js/dragdrop.js' %}"></script>
</html>

DesignTracer/app/templates/app/images_detail.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}
{% block content %}

        <div class="image-detail row">
            <div class="col-lg-4" id="image-img">
                <img src="{{ image.image_f }}" class="img-fluid">
            </div>
            <div class="col-lg-8" id="image-text">
            
            <p>{{ image.title }}</p>
            <table>
                <tr>
                    <th>主張の理解</th>
                </tr>
                <tr>
                    <td>{{ image.theme }}</td>
                </tr>
                <tr>
                    <th>分析/言語化</th>
                </tr>
                <tr>
                    <td>{{ image.break_down }}</td>
                </tr>
                <tr>
                    <th>抽象化：外せないキーになる部分は？</th>
                </tr>
                <tr>
                    <td>{{ image.key_point }}</td>
                </tr>
                <tr>
                    <th>投稿日時</th>
                </tr>
                <tr>
                    <td>{{ image.created_at }}</td>
                </tr>
            </table>
            </div>

        </div>
        <form method="post" action="{% url 'app:images_delete' image.id %}">{% csrf_token %}
            <button type="submit" class="btn btn-primary" onclick='return confirm("本当に削除しますか？");'>削除</button>
        </form>
{% endblock %}

DesignTracer/app/templates/app/img_list.html
<div class="img-container">
{% for img in images %}
    <div class='img'>
        <a href="{% url 'app:images_detail' img.id %}">
            <img src="{{ img.image_f }}" class="image-img">
        </a>
        <div class="image-info">
            <a href="{% url 'app:users_detail' img.user.id %}">@{{img.user}}</a>
        </div>
    </div>
{% empty %}
    <p>empty list</p>
{% endfor %}
</div>

DesignTracer/app/templates/app/index.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}
{% block content %}
    <form action="{% url 'app:index' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
        <div class="container">
        <div class="row">
            <div class="col-lg-6" id="drag-drop-area">
                <div class="drag-drop-inside">
                    <p class="drag-drop-info">ここにファイルをドロップ</p>
                    <p>または</p>
                    <p class="drag-drop-buttons"><input id="fileInput" type="file" value="ファイルを選択" name="image"></p>
                </div>
            </div>
            <div class="col-lg-6" id="text-area">
                <div class="form-group">
                    {{ form.title|add_class:'form-control' }}
                </div>
                <div class="form-group">
                    {{ form.theme|add_class:'form-control' }}
                </div>
                <div class="form-group">
                    {{ form.break_down|add_class:'form-control' }}
                </div>                
                <div class="form-group">
                    {{ form.key_point|add_class:'form-control' }}
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">サブミット</button>
        </div>
    </form>


    <!-- アップロードした画像を表示 -->

    {% include 'app/img_list.html' %}

    {% endblock %}

DesignTracer/app/templates/app/login.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}
{% block content %}

    <form method='post'>{%  csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="ログイン">
    </form>
{% endblock %}

DesignTracer/app/templates/app/mypage.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}
{% block content %}
  <h2 class='user-name'>@{{ user.username }} </h2>
  {% ifnotequal images.count 0 %}
    <p>投稿<strong>{{ images.count }}</strong>件</p>
  {% else %}
    {% if user == request.user %}
      <p>初めての投稿をしてみましょう！</p>
    {% endif %}
  {% endifnotequal %}

  {% include 'app/img_list.html' %}
{% endblock %}

DesignTracer/app/templates/app/signup.html
{% extends 'app/base.html' %}
{% load widget_tweaks %}
{% block content %}

    <h2>ユーザー登録</h2>

    <form method="post" action="{% url 'app:signup' %}">{% csrf_token %}
        <label>ユーザー名</label>
        {{form.username}}
        {{form.username.errors}}
        <br>
        <label>パスワード</label>
        {{form.password1}}
        {{form.password1.errors}}
        <br>
        <label>パスワード確認</label>
        {{form.password2}}
        {{form.password2.errors}}
        <br>
        <input type="submit" value="登録">
    </form>

    <p><a href="{% url 'app:login' %}">ログインはこちら</a></p>
{% endblock %}